app/index.html
app/scripts/i18n/i18n.js
app/views/main.html

I am not sure if the addition of "id" attributes that are required for the paper-char-counter leads us to some trouble!?

RB-201 #close RB-202 #close Added paper-char-counter and floatingLabel

---

app/elements/comments-list/comments-list.html
app/elements/requirements-list/requirements-list.html
app/scripts/app.js

Fixed incostinces
Added comments for every module in comments-list element

Comments cleanup

---

app/elements/requirements-list/requirements-list.html
app/index.html
app/locales/al.json
app/locales/de.json
app/locales/en.json
app/locales/ro.json
app/scripts/app.js
bower.json

Replaced most of the template-if markup with some more intelligent code. @albisema please review and merge soon. I am aware that the "realized" functionality is not completely working after the merge (e.g. first menu item of a requirement is empty), but I want to tackle that in another branch.

Template cleanup

---

app/elements/requirements-list/requirements-list.html
app/index.html
app/scripts/app.js

Removed all the 'active' and 'activeState' behavior as it led to duplicate/triplicate/quadruplicate markup. Also, 'activeState' was set to 'false' if 'selected' was 'active'... :confused: Renamed 'active' state to 'open', just like the API is using it. @albisema please review and merge if review positive. Thanks!

Realized state

---

app/elements/requirements-list/requirements-list.html

removed two dom-ifs, not a big thing. @albisema please review and merge.

Removed two dom-ifs. #RB-374

---

README.md

@albisema please review and merge.

Updated README with description

---

app/elements/requirements-list/requirements-list.html
app/index.html
app/scripts/app.js
app/styles/app-theme.html

@albisema please review and merge :)

Fixed typo and removed old contributors code #RB-372

---

app/elements/requirements-list/requirements-list.html

@albisema please review and merge.

Fixed the jump of the comments title when expanding/closing requirements #RB-389

---

app/elements/file-gallery/file-gallery.html
gulpfile.js
package.json

Added build gulp commands for live version and beta version
gulp serve:live and gulp serve:beta
builds the materials in dist folder and serves the files on browser to test before deployment

Gulp build #RB-387

---

elements/bread-crumb.html
elements/categories-menu.html
elements/requirement-card.html
src/view-requirement.html
src/view-requirements-list.html
src/view-requirements.html

When calling a URL with a requirement, it is now opened in a separate requirement view. Previously, the category view was opened and often users had to scroll down to find the requested requirement.

Requirement view

---

src/store/actions.ts
src/types/bazaar-api.ts

Followup to https://github.com/rwth-acis/RequirementsBazaar/pull/96
Requires a new rc to be deployed with the new direction object.

Update to new direction object

---

src/assets/layout/sass/_topbar.scss
src/components/AppTopbar.vue
src/components/CommentsList.vue
src/components/FilterPanel.vue
src/components/RequirementCard.vue
src/views/Category.vue
src/views/Project.vue

Responsive

---

src/App.vue
src/views/About.vue
src/views/Developer.vue
src/views/Landing.vue

About, Developer and link to privacy policy.

Info pages

---

src/store/actions.ts
src/store/getters.ts
src/store/mutations.ts
src/views/Projects.vue

Project search fix

---

.env.beta
.env.production
.github/workflows/release.yaml
.github/workflows/release_rc.yaml
README.md
package.json
src/api/bazaar.ts

Now it's possible to test the frontend locally, or build it for beta and production without changing any hard-coded URLs.

Environment specific build variables (e.g., API URL)

---

.env.dev-local-api
README.md
package.json
src/api/bazaar.ts
src/components/ProjectMembersList.vue
src/main.ts
src/router.ts
src/store/actions.ts
src/store/getters.ts
src/store/mutations.ts
src/store/state.ts
src/views/Project.vue
vueconfig.json

- Users can be added to a project with a specific role (Admin, Manager, Member)
- Members can be removed from a project
- Role of Members can be changed

Basic Project Member Management

---

.env.beta
.env.dev-local-api
.env.development
.env.production
CHANGELOG.md
README.md
package.json
src/App.vue
src/api/activities.ts
src/api/bazaar.ts
src/components/ActivityTracker.vue
src/components/CommentsList.vue
src/components/GlobalErrorMessage.vue
src/components/ProjectMembersList.vue
src/components/RequirementCard.vue
src/components/UserAvatar.vue
src/locales/en.json
src/main.ts
src/router.ts
src/service/ErrorHandler.ts
src/store/actions.ts
src/store/getters.ts
src/store/mutations.ts
src/store/state.ts
src/views/Project.vue
src/views/Requirement.vue
vite.config.ts
vueconfig.json

Check https://github.com/rwth-acis/RequirementsBazaar-WebFrontend/blob/develop/CHANGELOG.md#203---2021-12-20 for changes.
Everything except the fixed activity tracker link and the new UserAvatar component for showing default user icons should already be approved by pull requests into develop branch.
v2.0.3-rc.1 is already deployed on beta, so changes can be reviewed in action.

Release v2.0.3

---

src/components/ProjectEditor.vue
src/components/RequirementCard.vue
src/main.ts
src/types/bazaar-api.ts
src/views/Category.vue
src/views/Project.vue

Original changes from https://github.com/florisa/RequirementsBazaar-WebFrontend/tree/ba-zanier merged into this feature branch for testing with latest develop version.

Feature: Timeline Component

---

src/views/Project.vue

Guides user better through the process of connecting a GitHub repository to a Requirements Bazaar project (#161)

Feature/connect to GitHub guide

---

src/components/ActivityTracker.vue

opens the related project, category or requirement page when user clicks on an activity item
Implements #157

feat: navigate to target entity when activity item is clicked

---

src/api/bazaar.ts
src/components/ProjectCard.vue
src/locales/en.json
src/main.ts
src/store/actions.ts
src/store/getters.ts
src/store/mutations.ts
src/store/state.ts
src/views/Landing.vue

- Adds the top 3 projects by follower count as 'featured projects' to the landing page
- Links to the 'Requirements Bazaar' project for Requirements bazaar itself (always to prod instance)
Deployed for feedback on https://beta.requirements-bazaar.org/

Feature: Popular projects on landing page

---

src/components/ProjectCard.vue
src/main.ts

one tooltip for each metric (followers, categories, requirements)
fixes #201

feat: add tooltips to project card

---

src/locales/en.json
src/views/Landing.vue

Feature: change indicators for statistics

---

src/locales/en.json
src/views/Project.vue

- Fixes #191 
- Adds more instructions for users to configure Webhook

Fix: Link GitHub not working

---

src/views/Landing.vue

Embed Tweets of the ReqBaz Twitter account on landing page

Feature: Twitter timeline on landing page

---

src/components/CategoryEditor.vue
src/components/ProjectEditor.vue
src/components/RequirementEditor.vue

- Fixes: #214 
- Shows all existing validation errors for input fields of Requirement-, Category-, and Project-Editor components
- Adds validation of repository URL field (must be a URL)

Fix: Wrong validation message

---

src/router.ts
src/types/bazaar-api.ts
src/views/Admin.vue

**Added**:
- Button to link a Twitter account, which Requirements Bazaar uses for tweeting
- Button to post a test tweet in order to check everything is working

Feature: Simple Admin UI for Twitter

---

src/types/bazaar-api.ts
src/views/Admin.vue

Feature: Admin button for triggering new projects tweet manually

---

src/views/Projects.vue

feat: parse sort and search params from URL

---

.env.beta
.env.dev-local-api
.env.development
.env.production
README.md
src/api/bazaar.ts
src/components/RequirementCard.vue
src/components/RequirementDevTimeline.vue
src/locales/en.json
src/router.ts
src/store/actions.ts
src/store/getters.ts
src/store/mutations.ts
src/store/state.ts
src/ui-utils/requirement-menu-actions.ts
src/views/Requirement.vue

- Implements #211 
Replaces the re-used RequirementsCard component on the requirement details-page with an actual more-detailed page that can show all details for a requirement.
This will also add information that was not accessible before:
- a list of followers
- a list of developers
- overview of up and down votes

Feature: Requirement details page

---

src/components/RequirementCard.vue

Fix: Invalid share requirement URL

---

src/App.vue
src/components/CategoryEditor.vue
src/components/ProjectEditor.vue
src/components/RequirementEditor.vue
src/locales/en.json
src/service/ProgressService.ts
src/ui-utils/requirement-menu-actions.ts

Adds loading indicators when editing projects, categories, and requirements.

Feature: loading indicators

---

src/views/Category.vue

Fixes:
- https://github.com/rwth-acis/RequirementsBazaar-WebFrontend/issues/227

Fix: add requirement at correct position

---

package-lock.json
package.json
src/App.vue
src/components/DashboardList.vue
src/locales/en.json
src/main.ts
src/store/actions.ts
src/store/getters.ts
src/store/mutations.ts
src/store/state.ts
src/types/bazaar-api.ts
src/views/Requirement.vue

Added notifications for gamification, level and an achievement overview.

Gamification
